SCREEN_W,SCREEN_H=800,600
SCREEN_SIZE=(SCREEN_W,SCREEN_H)
PLAYER_MULTI = 2.9
BG_MULTI=2.68
FONT='FixedSys.ttf'
GRAVITY=1.0
BRICK_MULTI=2.69
ANTI_GRAVITY=0.3
GROUND_HEIGHT=SCREEN_H-62
ENEMY_MULTI=2.5
ENEMY_SPEED=1
COLOR_TYPE_GREEN = 0

# Piranha States
PIRANHA_REVEALING = 'PIRANHA_REVEALING'
PIRANHA_NORMAL = 'PIRANHA_NORMAL'
PIRANHA_HIDING = 'PIRANHA_HIDING'
PIRANHA_HIDDEN = 'PIRANHA_HIDDEN'